### ISSUE TITLE
Doesn't works with Rust rustc 1.12.0-nightly

### ISSUE THREAD

**Issue by JeanDenisVIDOT** [LeoTestard/rustlex#46]
`   Compiling rustlex_codegen v0.3.3
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:14:26: 14:35 error: unresolved import `syntax::ast::TokenTree`. There is no `TokenTree` in `syntax::ast` [E0432]
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:14 use syntax::ast::{Ident, TokenTree};
                                                                                                                         ^~~~~~~~~
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:14:26: 14:35 help: run `rustc --explain E0432` to see a detailed explanation
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:52:36: 52:44 error: the trait bound `syntax::ext::base::IdentMacroExpander: std::marker::Sized` is not satisfied [E0277]
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:52         syntax::ext::base::IdentTT(Box::new(rustlex), None, false)
                                                                                                                                   ^~~~~~~~
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:52:36: 52:44 help: run `rustc --explain E0277` to see a detailed explanation
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:52:36: 52:44 note: `syntax::ext::base::IdentMacroExpander` does not have a constant size known at compile-time 
/home/jeandenis/.cargo/registry/src/github.com-1ecc6299db9ec823/rustlex_codegen-0.3.3/lib.rs:52:36: 52:44 note: required by `std::boxed::<impl Box<T>>::new` 
error: aborting due to previous error 
error: Could not compile `rustlex_codegen`.`
